### ISSUE TITLE
ImportError: No module named 'google'

### ISSUE THREAD

**Issue by tropicaldandy** [zli117/EInk-Calendar#4]
Hi.  I tried to run the main.py, but the error in the title occurred.
Then I retried and still failed it after updating google-api-python-client.

I would appreciate it if you could give me some advice.

Best,

**Comment by zli117** [comment]
Just to mention: you need to install dependencies: `pip install -r requirements.txt`

**Comment by tropicaldandy** [comment]
Thank you for your advice.  
I could succeeded after 'pip3' install -r requirements.txt, for in my device both type of pythons exit and I tried to install it in python 2 before.
