### ISSUE TITLE
Installation Guide need Update

### ISSUE THREAD

**Issue by KunalGautam** [zli117/EInk-Calendar#5]
Following information might need to be added for people who are new.

Enable SPI Mode.
To Enable, pass following command 

`sudo raspi-config
`
Select **Interfacing Options**
Select **P4 SPI**
Select **Yes** when asked **Would you like the SPI interface to be enabled?**
It will prompt The SPI interface is enabled, press ok
Select **Finish** to exit raspi-config

Install required packages*
`sudo apt install libopenjp2-7 libtiff5
`

*Assuming user knows how to install pip/pip3 git and clone the project

**Comment by extremepayne** [comment]
Okay, but why not go straight to a PR? Why an issue?

**Comment by KunalGautam** [comment]
Pardon, not well versed in using PR. I'll try today to for it. Thank you for heads up :)
